autoindex off;
index index.php;

location / {
  try_files $uri $uri/ /index.php$is_args$args;
}

location ~ [^/]\.php(/|$) {
  if (!-f $document_root$fastcgi_script_name) {
    return 404;
  }
  fastcgi_split_path_info ^(.+\.php)(/.+)$;
  fastcgi_pass $backend_ip:$backend_port;
  include fastcgi.conf;
}